Upgrade 1.30.x to 1.33.x
OpsMx/front50-oes pull request #29
Opened 2024-05-17 05:52 UTC by aman-agrawal

Jira : https://devopsmx.atlassian.net/browse/OP-22085
Testing : Compile success, No new TCs failed bcoz of this change, deployed to ns=cvetarget aman1603/front50:16may1 - things LGTM
Note :
1. Will do the cleanup with separate PRs
2. Will modify github workflows & dockerfiles with separate PRs
3. Add/change front50 code wrt final kork publish (if required)

2024-05-17 05:53 UTC, aman-agrawal commented
I will not merge this PR to OES-1.30.1 (rather I will create new branch in opsmx/front50-oes)
To show the comparison of OSS-1.33.x & OES-1.30.1, this was done.

2024-06-06 11:06 UTC, meerajose commented
Verified commits and .gradle file. 
All files are present. 
All the package versions are latest.
Please see the comments.

2024-06-06 11:25 UTC, meerajose requested changes

2024-06-06 11:30 UTC, aman-agrawal commented on front50-test/front50-test.gradle
> +  testImplementation "org.apache.groovy:groovy:4.0.9"
https://github.com/OpsMx/front50-oes/blob/c2bdddc1bb25450a39e796ed0a95d445b937d40c/front50-test/front50-test.gradle#L23C3-L23C21

2024-06-06 11:30 UTC, aman-agrawal commented on front50-test/front50-test.gradle
> -  implementation("org.codehaus.groovy:groovy-all")
https://github.com/OpsMx/front50-oes/blob/c2bdddc1bb25450a39e796ed0a95d445b937d40c/front50-test/front50-test.gradle#L23C3-L23C21

2024-06-06 11:34 UTC, meerajose commented on front50-test/front50-test.gradle
> +  testImplementation "org.apache.groovy:groovy:4.0.9"
OK, Looks good to go

2024-06-06 11:35 UTC, meerajose commented on front50-test/front50-test.gradle
> -  implementation("org.codehaus.groovy:groovy-all")
Found it is not present in 1.30.1 as well. good to go

2024-06-06 11:37 UTC, meerajose commented on front50-web/front50-web.gradle
> -  implementation "io.swagger:swagger-annotations"
found it is not removed https://github.com/OpsMx/front50-oes/blob/OES-1.30.1/front50-web/front50-web.gradle
good to go

2024-06-06 11:39 UTC, meerajose approved these changes
Look good to merge

2024-06-06 16:32 UTC, j-sandy commented
@aman-agrawal Could you resolve the conflicts so that it can be ready to merge ? Meanwhile I continue reviewing it.

2024-06-06 16:43 UTC, aman-agrawal commented
> @aman-agrawal Could you resolve the conflicts so that it can be ready to merge ? Meanwhile I continue reviewing it.

https://github.com/OpsMx/front50-oes/pull/29#issuecomment-2116754586

2024-06-06 16:43 UTC, aman-agrawal commented
> Look good to merge

https://github.com/OpsMx/front50-oes/pull/29#issuecomment-2116754586

2024-06-06 17:00 UTC, j-sandy commented
So this PR is just for review, not to merge. I got it. It will be closed once reviewed.

2024-06-06 19:39 UTC, j-sandy commented on front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java
> +// import javax.validation.Valid;
@aman-agrawal Remove the commented line from code.

2024-06-06 19:39 UTC, j-sandy commented on front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoaderSpec.groovy
> +//import com.netflix.spinnaker.front50.config.S3Properties
Clean up commented code.

2024-06-06 19:39 UTC, j-sandy commented on front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
> +     //jooq.close()
Whether this block is required or not ? Plz verify, if not then clean it from here.

2024-06-06 19:39 UTC, j-sandy commented on front50-test/front50-test.gradle
> +  //testImplementation "net.logstash.logback:logstash-logback-encoder:4.11"
Clean up the commented code.

2024-06-06 19:39 UTC, j-sandy commented on front50-test/src/main/groovy/com/netflix/spinnaker/front50/utils/S3TestHelper.groovy
> +
If this segment of code is not required, please clean it up.

2024-06-07 03:37 UTC, aman-agrawal commented on front50-test/src/main/groovy/com/netflix/spinnaker/front50/utils/S3TestHelper.groovy
> +
https://github.com/OpsMx/front50-oes/pull/33

2024-06-07 03:37 UTC, aman-agrawal commented on front50-test/front50-test.gradle
> +  //testImplementation "net.logstash.logback:logstash-logback-encoder:4.11"
Done : https://github.com/OpsMx/front50-oes/pull/33

2024-06-07 03:38 UTC, aman-agrawal commented on front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
> +     //jooq.close()
This block not required.
Cleanup Done : https://github.com/OpsMx/front50-oes/pull/33

2024-06-07 03:38 UTC, aman-agrawal commented on front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java
> +// import javax.validation.Valid;
Done : https://github.com/OpsMx/front50-oes/pull/33

2024-06-07 03:38 UTC, aman-agrawal commented on front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoaderSpec.groovy
> +//import com.netflix.spinnaker.front50.config.S3Properties
Done : https://github.com/OpsMx/front50-oes/pull/33

2024-06-10 03:53 UTC, j-sandy approved these changes

2024-06-10 03:55 UTC, closed without merging